# Generated by Django 3.0.1 on 2020-04-29 13:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pacient', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nume', models.CharField(max_length=20)),
                ('prenume', models.CharField(max_length=20)),
                ('varsta', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('afectiune', models.CharField(max_length=20)),
                ('vaduv', models.BooleanField(default=False)),
                ('parola_pacient', models.CharField(max_length=20)),
                ('user_pacient', models.CharField(default='', max_length=20)),
                ('tel_urgenta', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{0,10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Tutore',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tutore', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nr_pacienti', models.IntegerField(default=0)),
                ('flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PacientParsing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('activitate', models.CharField(max_length=50)),
                ('dorinta', models.CharField(max_length=50)),
                ('tip_fire', models.CharField(max_length=50)),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Pacient')),
            ],
        ),
        migrations.AddField(
            model_name='pacient',
            name='tutore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Tutore'),
        ),
    ]
