# Generated by Django 3.0.1 on 2020-04-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacient',
            name='parola_pacient',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='user_pacient',
        ),
    ]
