# Generated by Django 3.0.1 on 2020-04-29 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20200429_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacient',
            name='nume',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='prenume',
        ),
    ]
