# Generated by Django 3.0.1 on 2020-05-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_auto_20200429_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientparsing',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pacientparsing',
            name='intrebare1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pacientparsing',
            name='intrebare2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pacientparsing',
            name='intrebare3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pacientparsing',
            name='mood_rating',
            field=models.IntegerField(default=0),
        ),
    ]
