# Generated by Django 3.0.1 on 2020-05-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_auto_20200506_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientparsing',
            name='negative_problems',
            field=models.CharField(default='def', max_length=1000),
            preserve_default=False,
        ),
    ]
