# Generated by Django 3.0.1 on 2020-05-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0006_auto_20200507_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientparsing',
            name='json_key',
            field=models.IntegerField(default=1),
        ),
    ]
