# Generated by Django 3.0.1 on 2020-05-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0010_auto_20200507_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientparsing',
            name='negative_problems',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
