# Generated by Django 3.0.1 on 2020-05-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0011_auto_20200507_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientparsing',
            name='json_key',
        ),
    ]
