# Generated by Django 3.0.1 on 2020-05-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0012_remove_pacientparsing_json_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientparsing',
            old_name='negative_problems',
            new_name='_negative_problems',
        ),
    ]
