# Generated by Django 3.0.1 on 2020-05-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0013_auto_20200507_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientparsing',
            name='contor_mesaje',
            field=models.IntegerField(default=0),
        ),
    ]
