# Generated by Django 3.0.1 on 2020-05-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0014_pacientparsing_contor_mesaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientparsing',
            name='flag',
        ),
        migrations.AddField(
            model_name='pacient',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
