# Generated by Django 3.0.1 on 2020-05-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0015_auto_20200509_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientparsing',
            name='contor_forms',
            field=models.IntegerField(default=0),
        ),
    ]
