# Generated by Django 3.0.1 on 2020-05-09 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0016_pacientparsing_contor_forms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientparsing',
            name='mood_rating',
        ),
        migrations.AddField(
            model_name='pacientparsing',
            name='mood_rating_list',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.int_list_validator]),
        ),
    ]
