# Generated by Django 3.0.1 on 2020-05-14 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0019_pacientparsing_flag_mood_parse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientparsing',
            name='flag_mood_parse',
        ),
    ]
