# Generated by Django 3.0.1 on 2020-05-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0022_pacientdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientdetails',
            name='hangout',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
