# Generated by Django 3.0.1 on 2020-05-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0023_auto_20200522_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientdetails',
            name='fav_activity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pacientdetails',
            name='fav_book',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pacientdetails',
            name='fav_game',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pacientdetails',
            name='fav_movie',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pacientdetails',
            name='fav_passion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pacientdetails',
            name='fav_song',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
