# Generated by Django 3.0.1 on 2020-05-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0024_auto_20200522_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientdetails',
            name='fav_activity',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pacientdetails',
            name='fav_book',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pacientdetails',
            name='fav_game',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pacientdetails',
            name='fav_movie',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pacientdetails',
            name='fav_passion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pacientdetails',
            name='fav_song',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pacientdetails',
            name='hangout',
            field=models.IntegerField(default=0),
        ),
    ]
