# Generated by Django 3.0.1 on 2020-06-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0025_auto_20200522_2001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiabetesParsing',
            new_name='LonelinessParsing',
        ),
    ]
